image: gcc:latest

before-script:
  - apt-get update --yes
  - apt-get install --yes cmake

build:
  script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
  artifacts:
    paths:
      - build/

test:
  script:
    - ./my_executable_test
  dependencies:
    - build
  artifacts:
    paths:
      - build/